=== carloschg1/Reto1-Grupo2/Departamentos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Departamentos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Departamento" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Id" type="xs:integer"/>
                            <xs:element name="NombreDep" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== carloschg1/Reto1-Grupo2/Departamentos.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<Departamentos xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
xs:noNamespaceSchemaLocation="Departamentos.xsd">
    <Departamento>
        <Id>1</Id>
        <NombreDep>COMERCIAL</NombreDep>
    </Departamento>
    <Departamento>
        <Id>2</Id>
        <NombreDep>COMPTABILITAT</NombreDep>
    </Departamento>
    <Departamento>
        <Id>3</Id>
        <NombreDep>INFORMÃ€TICA</NombreDep>
    </Departamento>
    <Departamento>
        <Id>4</Id>
        <NombreDep>PERSONAL</NombreDep>
    </Departamento>
</Departamentos>
