=== carloschg1/Reto1-Grupo2/Empleados.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Empleados">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Empleado" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="NIF" type="xs:string"/>
                            <xs:element name="Nombre" type="xs:string"/>
                            <xs:element name="Apellido1" type="xs:string"/>
                            <xs:element name="Apellido2" type="xs:string"/>
                            <xs:element name="cuenta" type="xs:string"/>
                            <xs:element name="Antigüedad" type="xs:string"/>
                            <xs:element name="N._de_afiliación_a_la_Seguridad_Social" type="xs:string"/>
                            <xs:element name="Categoría-Grupo_profesional" type="xs:string"/>
                            <xs:element name="Grupo_Cotización" type="xs:integer"/>
                            <xs:element name="email" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== carloschg1/Reto1-Grupo2/Empleados.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<Empleados xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
xs:noNamespaceSchemaLocation="Empleados.xsd">
    <Empleado>
        <NIF>12345713-J</NIF>
        <Nombre>JAVIER</Nombre>
        <Apellido1>CAMPOS</Apellido1>
        <Apellido2>VARGAS</Apellido2>
        <cuenta>jcamposv</cuenta>
        <Antigüedad>21/12/2022</Antigüedad>
        <N._de_afiliación_a_la_Seguridad_Social />
        <Categoría-Grupo_profesional>B1</Categoría-Grupo_profesional>
        <Grupo_Cotización>4</Grupo_Cotización>
        <email>jcamposv@empresa2.com</email>
    </Empleado>
    <Empleado>
        <NIF>123457199-B</NIF>
        <Nombre>ANGI</Nombre>
        <Apellido1>FILE</Apellido1>
        <Apellido2>MON</Apellido2>
        <cuenta>afilem</cuenta>
        <Antigüedad>21/03/2015</Antigüedad>
        <N._de_afiliación_a_la_Seguridad_Social />
        <Categoría-Grupo_profesional>A3</Categoría-Grupo_profesional>
        <Grupo_Cotización>7</Grupo_Cotización>
        <email>afilem@empresa2.com</email>
    </Empleado>
    <Empleado>
        <NIF>12345717-N</NIF>
        <Nombre>EVA</Nombre>
        <Apellido1>GARCIA</Apellido1>
        <Apellido2>ALAVES</Apellido2>
        <cuenta>egarciaa</cuenta>
        <Antigüedad>13/12/2017</Antigüedad>
        <N._de_afiliación_a_la_Seguridad_Social />
        <Categoría-Grupo_profesional>A3</Categoría-Grupo_profesional>
        <Grupo_Cotización>7</Grupo_Cotización>
        <email>egarciaa@empresa2.com</email>
    </Empleado>
    <Empleado>
        <NIF>12345714-K</NIF>
        <Nombre>EVA</Nombre>
        <Apellido1>MONCHO</Apellido1>
        <Apellido2>CARVALHO</Apellido2>
        <cuenta>emonchoc</cuenta>
        <Antigüedad>24/03/2023</Antigüedad>
        <N._de_afiliación_a_la_Seguridad_Social />
        <Categoría-Grupo_profesional>B1</Categoría-Grupo_profesional>
        <Grupo_Cotización>5</Grupo_Cotización>
        <email>emonchoc@empresa2.com</email>
    </Empleado>
    <Empleado>
        <NIF>12345684-G</NIF>
        <Nombre>MERE</Nombre>
        <Apellido1>PANTERA</Apellido1>
        <Apellido2>ROSA</Apellido2>
        <cuenta>mpanterar</cuenta>
        <Antigüedad>6/02/2013</Antigüedad>
        <N._de_afiliación_a_la_Seguridad_Social />
        <Categoría-Grupo_profesional>A2</Categoría-Grupo_profesional>
        <Grupo_Cotización>7</Grupo_Cotización>
        <email>mpanterar@empresa2.com</email>
    </Empleado>
    <Empleado>
        <NIF>12345683-F</NIF>
        <Nombre>JUAN</Nombre>
        <Apellido1>RIGOBERTO</Apellido1>
        <Apellido2>PICAPORTE</Apellido2>
        <cuenta>jrigobertop</cuenta>
        <Antigüedad>25/07/2017</Antigüedad>
        <N._de_afiliación_a_la_Seguridad_Social />
        <Categoría-Grupo_profesional>A2</Categoría-Grupo_profesional>
        <Grupo_Cotización>6</Grupo_Cotización>
        <email>jrigobertop@empresa2.com</email>
    </Empleado>
    <Empleado>
        <NIF>12345690-M</NIF>
        <Nombre>ANA</Nombre>
        <Apellido1>RUE</Apellido1>
        <Apellido2>PERCEBE</Apellido2>
        <cuenta>aruep</cuenta>
        <Antigüedad>26/05/2012</Antigüedad>
        <N._de_afiliación_a_la_Seguridad_Social />
        <Categoría-Grupo_profesional>B2</Categoría-Grupo_profesional>
        <Grupo_Cotización>7</Grupo_Cotización>
        <email>aruep@empresa2.com</email>
    </Empleado>
    <Empleado>
        <NIF>12345691-N</NIF>
        <Nombre>JOSE</Nombre>
        <Apellido1>SHIN</Apellido1>
        <Apellido2>CHAN</Apellido2>
        <cuenta>jshinc</cuenta>
        <Antigüedad>24/02/2017</Antigüedad>
        <N._de_afiliación_a_la_Seguridad_Social />
        <Categoría-Grupo_profesional>B2</Categoría-Grupo_profesional>
        <Grupo_Cotización>7</Grupo_Cotización>
        <email>jshinc@empresa2.com</email>
    </Empleado>
    <Empleado>
        <NIF>12345707-D</NIF>
        <Nombre>ANTONIO</Nombre>
        <Apellido1>ALABAU</Apellido1>
        <Apellido2>VALENCIA</Apellido2>
        <cuenta>aalabauv</cuenta>
        <Antigüedad>13/11/2022</Antigüedad>
        <N._de_afiliación_a_la_Seguridad_Social />
        <Categoría-Grupo_profesional>A2</Categoría-Grupo_profesional>
        <Grupo_Cotización>7</Grupo_Cotización>
        <email>aalabauv@empresa2.com</email>
    </Empleado>
    <Empleado>
        <NIF>12345716-M</NIF>
        <Nombre>JOHANN</Nombre>
        <Apellido1>ALBA</Apellido1>
        <Apellido2>CHAVES</Apellido2>
        <cuenta>jalbac</cuenta>
        <Antigüedad>8/04/2020</Antigüedad>
        <N._de_afiliación_a_la_Seguridad_Social />
        <Categoría-Grupo_profesional>B3</Categoría-Grupo_profesional>
        <Grupo_Cotización>4</Grupo_Cotización>
        <email>jalbac@empresa2.com</email>
    </Empleado>
    <Empleado>
        <NIF>12345692-O</NIF>
        <Nombre>VICOR</Nombre>
        <Apellido1>NANO</Apellido1>
        <Apellido2>UCHE</Apellido2>
        <cuenta>vnanou</cuenta>
        <Antigüedad>3/05/2021</Antigüedad>
        <N._de_afiliación_a_la_Seguridad_Social />
        <Categoría-Grupo_profesional>A1</Categoría-Grupo_profesional>
        <Grupo_Cotización>5</Grupo_Cotización>
        <email>vnanou@empresa2.com</email>
    </Empleado>
    <Empleado>
        <NIF>12345718-A</NIF>
        <Nombre>PEDRO</Nombre>
        <Apellido1>PULGAR</Apellido1>
        <Apellido2>CITO</Apellido2>
        <cuenta>ppulgarc</cuenta>
        <Antigüedad>23/01/2022</Antigüedad>
        <N._de_afiliación_a_la_Seguridad_Social />
        <Categoría-Grupo_profesional>A2</Categoría-Grupo_profesional>
        <Grupo_Cotización>1</Grupo_Cotización>
        <email>ppulgarc@empresa2.com</email>
    </Empleado>
    <Empleado>
        <NIF>12345720-C</NIF>
        <Nombre>MARIA</Nombre>
        <Apellido1>SEGIS</Apellido1>
        <Apellido2>OLIVIO</Apellido2>
        <cuenta>msegiso</cuenta>
        <Antigüedad>7/11/2021</Antigüedad>
        <N._de_afiliación_a_la_Seguridad_Social />
        <Categoría-Grupo_profesional>A3</Categoría-Grupo_profesional>
        <Grupo_Cotización>5</Grupo_Cotización>
        <email>msegiso@empresa2.com</email>
    </Empleado>
    <Empleado>
        <NIF>12345693-P</NIF>
        <Nombre>TONI</Nombre>
        <Apellido1>TIN</Apellido1>
        <Apellido2>TIN</Apellido2>
        <cuenta>ttint</cuenta>
        <Antigüedad>7/08/2011</Antigüedad>
        <N._de_afiliación_a_la_Seguridad_Social />
        <Categoría-Grupo_profesional>B2</Categoría-Grupo_profesional>
        <Grupo_Cotización>4</Grupo_Cotización>
        <email>ttint@empresa2.com</email>
    </Empleado>
    <Empleado>
        <NIF>12345709-F</NIF>
        <Nombre>SUSANA</Nombre>
        <Apellido1>VALENCIA</Apellido1>
        <Apellido2>MONCHO</Apellido2>
        <cuenta>svalenciam</cuenta>
        <Antigüedad>14/11/2022</Antigüedad>
        <N._de_afiliación_a_la_Seguridad_Social />
        <Categoría-Grupo_profesional>B2</Categoría-Grupo_profesional>
        <Grupo_Cotización>7</Grupo_Cotización>
        <email>svalenciam@empresa2.com</email>
    </Empleado>
    <Empleado>
        <NIF>12345689-L</NIF>
        <Nombre>TUSO</Nombre>
        <Apellido1>ZIPI</Apellido1>
        <Apellido2>ZAPEL</Apellido2>
        <cuenta>tzipiz</cuenta>
        <Antigüedad>28/08/2015</Antigüedad>
        <N._de_afiliación_a_la_Seguridad_Social />
        <Categoría-Grupo_profesional>A3</Categoría-Grupo_profesional>
        <Grupo_Cotización>3</Grupo_Cotización>
        <email>tzipiz@empresa2.com</email>
    </Empleado>
    <Empleado>
        <NIF>12345715-L</NIF>
        <Nombre>RODRIGO</Nombre>
        <Apellido1>CHAVES</Apellido1>
        <Apellido2>CAMPOS</Apellido2>
        <cuenta>rchavesc</cuenta>
        <Antigüedad>4/08/2020</Antigüedad>
        <N._de_afiliación_a_la_Seguridad_Social />
        <Categoría-Grupo_profesional>A2</Categoría-Grupo_profesional>
        <Grupo_Cotización>5</Grupo_Cotización>
        <email>rchavesc@empresa2.com</email>
    </Empleado>
    <Empleado>
        <NIF>12345695-R</NIF>
        <Nombre>JESU</Nombre>
        <Apellido1>COMI</Apellido1>
        <Apellido2>CLANDIA</Apellido2>
        <cuenta>jcomic</cuenta>
        <Antigüedad>9/08/2013</Antigüedad>
        <N._de_afiliación_a_la_Seguridad_Social />
        <Categoría-Grupo_profesional>A2</Categoría-Grupo_profesional>
        <Grupo_Cotización>4</Grupo_Cotización>
        <email>jcomic@empresa2.com</email>
    </Empleado>
    <Empleado>
        <NIF>12345686-I</NIF>
        <Nombre>ISA</Nombre>
        <Apellido1>GOTERA</Apellido1>
        <Apellido2>OTILIO</Apellido2>
        <cuenta>igoterao</cuenta>
        <Antigüedad>3/04/2012</Antigüedad>
        <N._de_afiliación_a_la_Seguridad_Social />
        <Categoría-Grupo_profesional>A1</Categoría-Grupo_profesional>
        <Grupo_Cotización>7</Grupo_Cotización>
        <email>igoterao@empresa2.com</email>
    </Empleado>
    <Empleado>
        <NIF>12345721-D</NIF>
        <Nombre>MANU</Nombre>
        <Apellido1>TOM</Apellido1>
        <Apellido2>JERRY</Apellido2>
        <cuenta>mtomj</cuenta>
        <Antigüedad>4/03/2012</Antigüedad>
        <N._de_afiliación_a_la_Seguridad_Social />
        <Categoría-Grupo_profesional>A1</Categoría-Grupo_profesional>
        <Grupo_Cotización>3</Grupo_Cotización>
        <email>mtomj@empresa2.com</email>
    </Empleado>
    <Empleado>
        <NIF>12345694-Q</NIF>
        <Nombre>XIMO</Nombre>
        <Apellido1>ABEJA</Apellido1>
        <Apellido2>MAYA</Apellido2>
        <cuenta>xabejam</cuenta>
        <Antigüedad>4/12/2016</Antigüedad>
        <N._de_afiliación_a_la_Seguridad_Social />
        <Categoría-Grupo_profesional>B1</Categoría-Grupo_profesional>
        <Grupo_Cotización>7</Grupo_Cotización>
        <email>xabejam@empresa2.com</email>
    </Empleado>
    <Empleado>
